# Generated by Django 2.2.11 on 2020-05-12 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_name', models.CharField(max_length=200)),
                ('profile_image', imagekit.models.fields.ProcessedImageField(default='default.png', upload_to='speakers/')),
                ('biography', models.TextField(default='', help_text='The bio of the speaker', max_length=600, null=True)),
                ('company', models.CharField(blank=True, default='', help_text='Name of Organization speaker is from. eg. Google', max_length=200, null=True)),
                ('twitter', models.CharField(blank=True, default='', help_text="Please enter only the user name eg.'mawy_7' ", max_length=100, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_visible', models.BooleanField(default=False)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='speaker_name')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talk_title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('talk_type', models.CharField(choices=[('Talk', 'Talk'), ('Tutorial', 'Tutorial')], default='', max_length=20)),
                ('talk_abstract', models.TextField(default='')),
                ('talk_description', models.TextField(default='')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_visible', models.BooleanField(default=False)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='talk_title')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('speaker_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speakers.Speaker')),
            ],
        ),
    ]
