# Generated by Django 2.2.11 on 2020-05-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='bio',
            field=models.TextField(help_text='The bio of the speaker', max_length=200),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='company',
            field=models.CharField(blank=True, default='', help_text='Name of Organization speaker is from. eg. Google', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='talk',
            name='talk_abstract',
            field=models.TextField(default=''),
        ),
    ]
