# Generated by Django 2.2.11 on 2020-05-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='github',
            field=models.CharField(blank=True, default='', help_text="Please enter only the user name eg.'mawy_7' ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='linkdin',
            field=models.CharField(blank=True, default='', help_text="Please enter only the user name eg.'mawy_7' ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='talk_abstract',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='speaker',
            name='talk_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='speaker',
            name='talk_title',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='talk_type',
            field=models.CharField(choices=[('Talk', 'Talk'), ('Tutorial', 'Tutorial')], default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='Talk',
        ),
    ]
