# Generated by Django 2.2.11 on 2020-06-26 18:22

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', imagekit.models.fields.ProcessedImageField(default='default.png', upload_to='speakers/')),
                ('speaker_name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='speaker',
            name='profile_image',
            field=models.ForeignKey(default='default.png', on_delete=django.db.models.deletion.CASCADE, to='speakers.ProfileImage'),
        ),
    ]
