# Generated by Django 2.2.5 on 2020-01-30 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speaker',
            old_name='updated_by',
            new_name='created_by',
        ),
    ]
