# Generated by Django 2.2.11 on 2020-05-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0002_auto_20200509_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='bio',
            field=models.TextField(default='', help_text='The bio of the speaker', max_length=200, null=True),
        ),
    ]
