# Generated by Django 2.2.11 on 2020-06-26 18:35

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0002_auto_20200626_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='profile_image',
            field=imagekit.models.fields.ProcessedImageField(default='speakers/speaker.png', upload_to='speakers/'),
        ),
    ]
