# Generated by Django 2.2.11 on 2020-05-09 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0003_auto_20200509_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='position',
        ),
    ]
