# Generated by Django 2.2.11 on 2020-05-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0003_auto_20200512_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='youtube_iframe_url',
            field=models.URLField(blank=True, default='', help_text='Link to Youtube Iframe'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='youtube_vide_url',
            field=models.URLField(blank=True, default='', help_text='Link to Talk on youtube Video'),
        ),
    ]
