# Generated by Django 2.2.5 on 2020-01-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0003_auto_20200130_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='profile_image',
            field=models.ImageField(default='speaker.png', upload_to='speakers/'),
        ),
    ]
