# Generated by Django 2.2.11 on 2020-06-26 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0003_auto_20200626_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='talk_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='speaker',
            name='talk_title',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='talk_type',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='speakers.Talktype'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='youtube_iframe_url',
            field=models.URLField(blank=True, default='', help_text='Link to Youtube Iframe'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='youtube_vide_url',
            field=models.URLField(blank=True, default='', help_text='Link to Talk on youtube Video'),
        ),
    ]
