# Generated by Django 2.2.11 on 2020-06-26 18:50

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0004_auto_20200626_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='speaker_name',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='talk_type',
        ),
        migrations.AlterField(
            model_name='speaker',
            name='profile_image',
            field=imagekit.models.fields.ProcessedImageField(default='speakers/speaker.png', upload_to='speakers/'),
        ),
        migrations.DeleteModel(
            name='ProfileImage',
        ),
        migrations.DeleteModel(
            name='Talk',
        ),
    ]
