# Generated by Django 2.2.11 on 2020-05-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0005_remove_speaker_talk_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='talk_abstract',
        ),
        migrations.AddField(
            model_name='speaker',
            name='talk_type',
            field=models.CharField(choices=[('Talk', 'Talk'), ('Tutorial', 'Tutorial')], default='', max_length=20),
        ),
    ]
