# Generated by Django 2.2.11 on 2020-05-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0005_auto_20200511_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='biography',
            field=models.TextField(default='', help_text='The bio of the speaker', max_length=600, null=True),
        ),
    ]
