# Generated by Django 2.2.5 on 2020-01-31 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0006_auto_20200131_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='talk_title',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='speaker',
            name='talk_type',
            field=models.CharField(choices=[('Talk', 'Talk'), ('Tutorial', 'Tutorial')], default=' ', max_length=20),
        ),
    ]
