# Generated by Django 2.2.11 on 2020-06-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0007_auto_20200626_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='linkedin',
            field=models.CharField(blank=True, default='', help_text="Please enter only the user name eg.'/mawy_7' ", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='youtube_iframe_url',
            field=models.TextField(blank=True, default='', help_text='Link to Youtube Iframe'),
        ),
    ]
