# Generated by Django 2.2.5 on 2020-03-13 17:50

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0008_speaker_talk_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='profile_image',
            field=imagekit.models.fields.ProcessedImageField(default='speaker.png', upload_to='speakers/'),
        ),
    ]
