# Generated by Django 2.2.11 on 2020-05-14 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('speakers', '0008_auto_20200512_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talktype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talk_type', models.CharField(choices=[('', ''), ('Talk', 'Talk'), ('Tutorial', 'Tutorial')], default='', max_length=20)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='talk_description',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='talk_title',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='talk_type',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='youtube_iframe_url',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='youtube_vide_url',
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talk_title', models.CharField(default='', max_length=200, null=True)),
                ('talk_description', models.TextField(default='')),
                ('youtube_vide_url', models.URLField(blank=True, default='', help_text='Link to Talk on youtube Video')),
                ('youtube_iframe_url', models.URLField(blank=True, default='', help_text='Link to Youtube Iframe')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_visible', models.BooleanField(default=False)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='talk_title')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('speaker_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speakers.Speaker')),
                ('talk_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speakers.Talktype')),
            ],
        ),
    ]
