# Generated by Django 2.2.11 on 2020-06-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0008_auto_20200627_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='youtube_iframe_url',
            field=models.URLField(blank=True, default='', help_text='Link to Youtube Iframe', max_length=300),
        ),
    ]
