# Generated by Django 2.2.11 on 2020-05-15 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0009_auto_20200514_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='talktype',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
