# Generated by Django 2.2.11 on 2020-06-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0009_auto_20200627_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='talk_type',
        ),
        migrations.AddField(
            model_name='speaker',
            name='talk_type',
            field=models.ManyToManyField(default='', null=True, to='speakers.Talktype'),
        ),
        migrations.AlterField(
            model_name='talktype',
            name='talk_type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
