# Generated by Django 2.2.5 on 2020-03-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0009_auto_20200313_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='linkedin',
            field=models.CharField(blank=True, default='', help_text='Please enter only the user name eg. in/mawy7 ', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='talk_title',
            field=models.CharField(blank=True, default=' ', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='twitter',
            field=models.CharField(blank=True, default='', help_text="Please enter only the user name eg.'mawy_7' ", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='website',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
