# Generated by Django 2.2.11 on 2020-05-15 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0010_talktype_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speaker',
            old_name='linkdin',
            new_name='linkedin',
        ),
    ]
