# Generated by Django 2.2.11 on 2020-06-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0010_auto_20200627_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='talk_type',
            field=models.ManyToManyField(default='', to='speakers.Talktype'),
        ),
    ]
