# Generated by Django 2.2.5 on 2020-03-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0010_auto_20200313_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='bio',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
