# Generated by Django 2.2.11 on 2020-06-27 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0012_auto_20200627_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talktype',
            name='talk_type',
            field=models.CharField(choices=[('', ''), ('Keynote', 'Keynote'), ('Talk', 'Talk'), ('Lightning talk', 'Lightning talk'), ('Tutorial', 'Tutorial')], default='', max_length=20),
        ),
    ]
