# Generated by Django 2.2.11 on 2020-06-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0013_auto_20200627_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talktype',
            name='talk_type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
