# Generated by Django 2.2.11 on 2020-06-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0014_auto_20200627_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='audience_type',
            field=models.ManyToManyField(to='speakers.Audiencetype'),
        ),
    ]
