# Generated by Django 2.2.11 on 2020-06-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0015_auto_20200627_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='audience_type',
        ),
        migrations.AddField(
            model_name='speaker',
            name='beginner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='speaker',
            name='expert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='speaker',
            name='intermediate',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Audiencetype',
        ),
    ]
