# Generated by Django 2.2.11 on 2020-06-27 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0016_auto_20200627_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speaker',
            old_name='beginner',
            new_name='beginner_level',
        ),
        migrations.RenameField(
            model_name='speaker',
            old_name='expert',
            new_name='expert_level',
        ),
        migrations.RenameField(
            model_name='speaker',
            old_name='intermediate',
            new_name='intermediate_level',
        ),
    ]
