# Generated by Django 2.2.11 on 2020-06-28 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0017_auto_20200627_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='biography',
            field=models.TextField(default='', help_text='The bio of the speaker', null=True),
        ),
    ]
