# Generated by Django 2.2.11 on 2020-06-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0018_auto_20200628_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='all_level',
            field=models.BooleanField(default=False),
        ),
    ]
