# Generated by Django 2.2.11 on 2020-07-09 22:44

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0019_speaker_all_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='biography',
            field=tinymce.models.HTMLField(default='', help_text='The bio of the speaker', null=True, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='talk_description',
            field=tinymce.models.HTMLField(default='', null=True, verbose_name='Talk Description'),
        ),
    ]
