# Generated by Django 2.2.11 on 2020-07-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0020_auto_20200709_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='speaker_name',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
