# Generated by Django 5.0.2 on 2024-02-29 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0021_auto_20200726_1919'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Speaker',
        ),
        migrations.DeleteModel(
            name='Talktype',
        ),
    ]
