# Generated by Django 5.0.2 on 2024-02-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_safety_guideline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health_safety_guideline',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
