# Generated by Django 3.2 on 2022-08-23 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='sponsor name')),
                ('category', models.CharField(blank=True, choices=[('Headline', 'Headline - ($8,000)'), ('Platinum', 'Platinum ($6,000)'), ('Diamond', 'Diamond ($3,500)'), ('Gold', 'Gold ($2,500)'), ('Silver', 'Silver - ($1,000)'), ('Bronze', 'Bronze - ($500)'), ('Diversity', 'Diversity'), ('Special', 'Special'), ('Individual', 'Individual'), ('Other', 'Other')], max_length=25, null=True)),
                ('logo', models.ImageField(blank=True, max_length=255, null=True, upload_to='sponsors/')),
                ('type', models.CharField(choices=[('C', 'Corporate Sponsor'), ('S', 'Special Sponsor'), ('D', 'Diversity'), ('I', 'Individual Sponsor')], max_length=1, verbose_name='sponsor type')),
                ('is_visible', models.BooleanField(default=False)),
                ('website', models.URLField(blank=True, default='', help_text='Link to Sponsor website')),
                ('twitter', models.CharField(blank=True, default='', help_text="Please enter only the user name eg.'mawy_7' ", max_length=100, null=True)),
                ('linkedin', models.CharField(blank=True, default='', help_text="Please enter only the user name eg.'mawy_7' ", max_length=100, null=True)),
                ('biography', models.TextField(blank=True, default='', help_text='Description of the Sponsor', null=True)),
                ('show_biography', models.BooleanField(default=True, help_text='Untick if the company only want their logo displayed on our website. Not all companies want their information on the site.')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
