# Generated by Django 3.2 on 2022-09-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='show_biography',
            field=models.BooleanField(default=False, help_text='Untick if the company only want their logo displayed on our website. Not all companies want their information on the site.'),
        ),
    ]
