# Generated by Django 3.2 on 2022-10-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_alter_sponsor_show_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='category',
            field=models.CharField(blank=True, choices=[('Headline', 'Headline - ($8,000)'), ('Platinum', 'Platinum ($6,000)'), ('Diamond', 'Diamond ($3,500)'), ('Gold', 'Gold ($2,500)'), ('Silver', 'Silver - ($1,000)'), ('Bronze', 'Bronze - ($500)'), ('Diversity', 'Diversity'), ('Special', 'Special'), ('Community', 'Community'), ('Individual', 'Individual'), ('Other', 'Other')], max_length=25, null=True),
        ),
    ]
