# Generated by Django 2.2.11 on 2020-05-20 17:01

from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0014_auto_20180719_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={},
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='type',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='talk_title'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='sponsor_type',
            field=models.CharField(choices=[('C', 'Corporate Sponsor'), ('S', 'Special Sponsor'), ('I', 'Individual Sponsor')], default='', max_length=1, verbose_name='sponsor type'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='category',
            field=models.CharField(choices=[('Headline', 'Headline - $16000'), ('Platinum', 'Platinum - $8000'), ('Diamond', 'Diamond - $4000'), ('Gold', 'Gold - $2000'), ('Silver', 'Silver - 1000'), ('Bronze', 'Bronze - 500'), ('Individual', 'Individual'), ('Other', 'Other')], max_length=15),
        ),
    ]
