# Generated by Django 2.2.11 on 2020-05-21 12:34

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0015_auto_20200520_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
    ]
