# Generated by Django 5.0.2 on 2024-09-04 07:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        ('talks', '0018_alter_proposal_talk_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_day', models.CharField(help_text='The name of the conference day (e.g., Day 1, Day 2).', max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Conference Day',
                'verbose_name_plural': 'Conference Days',
                'ordering': ['conference_day'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(default='', help_text='The name or number of the conference room.', max_length=50, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['room_name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_live', models.BooleanField(default=False, help_text='Indicates if the schedule is live and visible to all users.')),
            ],
            options={
                'verbose_name': 'Schedule Visibility',
                'verbose_name_plural': 'Schedule Visibility',
            },
        ),
        migrations.CreateModel(
            name='TalkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_an_event', models.BooleanField(default=False)),
                ('fa_icon', models.CharField(blank=True, default='', max_length=100)),
                ('event_url', models.CharField(blank=True, default='', help_text='URL to the event', max_length=250)),
                ('external_url', models.CharField(blank=True, default='', help_text='External link to the event', max_length=250)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('day_session', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], default='', max_length=10)),
                ('rowspan', models.CharField(blank=True, default='', help_text='Use to determine how this talk fits in its time allocation', max_length=10)),
                ('concurrent_talk', models.BooleanField(default=False)),
                ('is_a_keynote_speaker', models.BooleanField(default=False)),
                ('is_a_panel', models.BooleanField(default=False)),
                ('allocated_room', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='schedule.room')),
                ('conference_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.day')),
                ('event', models.ForeignKey(blank=True, help_text="Select an Event if it's not a Talk", null=True, on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('talk', models.ForeignKey(blank=True, help_text="Select a Talk if it's a Speaker giving a talk", null=True, on_delete=django.db.models.deletion.CASCADE, to='talks.proposal')),
            ],
            options={
                'verbose_name_plural': 'Talk Schedules',
                'managed': True,
            },
        ),
    ]
