# Generated by Django 2.2.11 on 2020-07-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_talkschedule_talk_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkschedule',
            name='talk_url',
            field=models.CharField(blank=True, default='', help_text='Please enter the url to the speaker talk', max_length=50, null=True),
        ),
    ]
