# Generated by Django 2.2.11 on 2020-07-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20200726_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkschedule',
            name='track_colour',
            field=models.CharField(default='primary', help_text="Colour to indicate it's track type", max_length=50, null=True),
        ),
    ]
