# Generated by Django 5.0.2 on 2024-02-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
