# Generated by Django 5.0.2 on 2024-03-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.CharField(blank=True, default='', help_text='Please your LinkedIn link ', max_length=100, null=True),
        ),
    ]
