# Generated by Django 2.2.11 on 2020-06-30 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeynoteSpeaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_name', models.CharField(default='', max_length=200)),
                ('profile_image', imagekit.models.fields.ProcessedImageField(default='speakers/speaker.png', upload_to='speakers/')),
                ('profession', models.CharField(blank=True, default='', help_text="Speaker's profession. eg. Software Developer", max_length=200, null=True)),
                ('organization', models.CharField(blank=True, default='', help_text="Speaker's Organization. eg. Google", max_length=200, null=True)),
                ('country', models.CharField(blank=True, default='', help_text='City and Country the speaker is from eg. Accra, Ghana', max_length=100, null=True)),
                ('biography', models.TextField(default='', help_text='The bio of the speaker', null=True)),
                ('twitter', models.CharField(blank=True, default='', help_text="Please enter only the user name eg.'mawy_7' ", max_length=100, null=True)),
                ('github', models.CharField(blank=True, default='', help_text="Please enter only the user name eg.'mawy_7' ", max_length=100, null=True)),
                ('linkedin', models.CharField(blank=True, default='', help_text="Please enter only the user name eg.'/mawy_7' ", max_length=100, null=True)),
                ('youtube_vide_url', models.URLField(blank=True, default='', help_text='Link to Talk on youtube Video')),
                ('youtube_iframe_url', models.URLField(blank=True, default='', help_text='Link to Youtube Iframe', max_length=300)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_visible', models.BooleanField(default=False)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='speaker_name')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
