# Generated by Django 2.2.11 on 2020-06-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keynotespeaker',
            name='organization',
            field=models.CharField(blank=True, default='', help_text="KeynoteSpeaker's Organization. eg. Google", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='keynotespeaker',
            name='profession',
            field=models.CharField(blank=True, default='', help_text="KeynoteSpeaker's profession. eg. Software Developer", max_length=200, null=True),
        ),
    ]
