# Generated by Django 2.2.11 on 2020-06-30 12:35

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200630_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keynotespeaker',
            name='profile_image',
            field=imagekit.models.fields.ProcessedImageField(default='keynotes/speaker.png', upload_to='keynotes/'),
        ),
    ]
