# Generated by Django 2.2.11 on 2020-07-11 16:50

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200630_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keynotespeaker',
            name='biography',
            field=tinymce.models.HTMLField(default='', help_text='The bio of the speaker', null=True, verbose_name='Biography'),
        ),
    ]
