# Generated by Django 2.2.11 on 2024-02-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200711_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('home_info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='KeynoteSpeaker',
        ),
    ]
