# Generated by Django 2.2.11 on 2024-02-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20240226_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventyear',
            name='template_name',
            field=models.CharField(default='home/home.html', help_text="Enter the template file name for this event year. Example: 'events/2024_home.html'", max_length=255),
        ),
    ]
