# Generated by Django 2.2.11 on 2024-02-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_eventyear_template_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventyear',
            options={'verbose_name': 'Event Year', 'verbose_name_plural': 'Event Years'},
        ),
        migrations.RemoveField(
            model_name='eventyear',
            name='template_name',
        ),
        migrations.AddField(
            model_name='eventyear',
            name='template_path',
            field=models.CharField(default='home/home.html', help_text="Path to the year's templates, e.g., '2020/home/home.html'", max_length=255),
        ),
    ]
