# Generated by Django 3.2 on 2022-08-14 13:36

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fin_aid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Financial Assistance PyCon Africa', max_length=250)),
                ('financial_assistance', markdownx.models.MarkdownxField(default='', help_text='[Supports Markdown] - Financial Assistance PyCon Africa.')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='fin_aid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
