# Generated by Django 3.2 on 2022-08-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_aid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_aid',
            name='google_form_formfacade_code',
            field=models.TextField(blank=True, default='', help_text='Link to your google form'),
        ),
    ]
