# Generated by Django 5.0.2 on 2024-02-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_aid', '0002_fin_aid_google_form_formfacade_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fin_aid',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
