# Generated by Django 2.2.11 on 2020-06-09 11:08

from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='sponsor name')),
                ('category', models.CharField(choices=[('Headline', 'Headline - $16000'), ('Platinum', 'Platinum - $8000'), ('Diamond', 'Diamond - $4000'), ('Gold', 'Gold - $2000'), ('Silver', 'Silver - 1000'), ('Bronze', 'Bronze - 500'), ('Individual', 'Individual'), ('Other', 'Other')], max_length=15)),
                ('logo', models.ImageField(blank=True, max_length=255, null=True, upload_to='sponsors/')),
                ('sponsor_type', models.CharField(choices=[('C', 'Corporate Sponsor'), ('S', 'Special Sponsor'), ('I', 'Individual Sponsor')], default='', max_length=1, verbose_name='sponsor type')),
                ('url', models.URLField(blank=True, default='', help_text='Link to Sponsor website')),
                ('description', models.TextField(blank=True, default='', help_text='Description of the Sponsor', null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_visible', models.BooleanField(default=False)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
            ],
        ),
    ]
