# Generated by Django 2.2.11 on 2020-06-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='category',
            field=models.CharField(choices=[('Headline', 'headline'), ('Platinum', 'platinum'), ('Diamond', 'diamond'), ('Gold', 'gold'), ('Silver', 'silver'), ('Bronze', 'bronze'), ('Individual', 'individual'), ('Other', 'other')], max_length=15),
        ),
    ]
