# Generated by Django 2.2.11 on 2020-06-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_sponsors', '0002_auto_20200609_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='url',
            new_name='website',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='linkedin',
            field=models.CharField(blank=True, default='', help_text="Please enter only the user name eg.'mawy_7' ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='twitter',
            field=models.CharField(blank=True, default='', help_text="Please enter only the user name eg.'mawy_7' ", max_length=100, null=True),
        ),
    ]
