# Generated by Django 2.2.11 on 2020-06-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_sponsors', '0004_auto_20200609_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='show_biography',
            field=models.BooleanField(default=True, help_text='Untick if the company only want their logo displayed on our website. Not all companies want their information on the site.'),
        ),
    ]
