# Generated by Django 2.2.11 on 2020-06-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_sponsors', '0005_auto_20200609_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='youtube',
            field=models.URLField(blank=True, default='', help_text="Please enter organization youtube channel link' ", max_length=100, null=True),
        ),
    ]
