# Generated by Django 5.0.2 on 2024-03-05 15:54

import django.db.models.deletion
import markdownx.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0008_pyconevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorshipTier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Sponsorship Tier name. eg, Gold, Silver', max_length=100)),
                ('amount', models.CharField(blank=True, help_text='Sponsorship Tier Amount eg, $1000', max_length=25)),
                ('no_needed', models.CharField(blank=True, help_text='Sponsorship Tier needed', max_length=25)),
                ('no_available', models.CharField(blank=True, help_text='Sponsorship Tier available', max_length=25)),
                ('colour', models.CharField(default='#000', help_text='Shadow colour for tier eg, #cd7f32', max_length=25)),
                ('details', markdownx.models.MarkdownxField(help_text='[Supports Markdown] - Sponsorship Tier.')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorship_tier_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SponsorUsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Support PyCon Africa', max_length=250)),
                ('why_sponsor_us', markdownx.models.MarkdownxField(help_text='[Supports Markdown] - Support PyCon Africa.')),
                ('special_sponsorship', markdownx.models.MarkdownxField(help_text='[Supports Markdown] - Special sponsorship package.')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('event_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supportus_pages', to='home.eventyear')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supportus_pages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
