# Generated by Django 5.0.2 on 2024-03-05 18:11

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorshiptier',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Order in which the tier should be displayed.'),
        ),
        migrations.AddField(
            model_name='sponsoruspage',
            name='prospectus_link',
            field=models.URLField(blank=True, help_text='Link to the sponsorship prospectus.'),
        ),
        migrations.AlterField(
            model_name='sponsorshiptier',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Sponsorship Tier Amount eg, 1000.00', max_digits=10),
        ),
        migrations.AlterField(
            model_name='sponsorshiptier',
            name='details',
            field=markdownx.models.MarkdownxField(help_text='[Supports Markdown] - Detailed description of the tier.'),
        ),
        migrations.AlterField(
            model_name='sponsorshiptier',
            name='no_available',
            field=models.IntegerField(help_text='Number of sponsorships available.'),
        ),
        migrations.AlterField(
            model_name='sponsorshiptier',
            name='no_needed',
            field=models.IntegerField(help_text='Number of sponsorships needed.'),
        ),
        migrations.CreateModel(
            name='AdditionalResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='sponsorship_resources/')),
                ('description', models.TextField(blank=True)),
                ('sponsorship_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_resources', to='sponsor_us.sponsorshiptier')),
            ],
        ),
        migrations.CreateModel(
            name='SponsorshipBenefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='sponsor_us.sponsorshiptier')),
            ],
        ),
    ]
