# Generated by Django 5.0.2 on 2024-03-05 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_us', '0004_remove_additionalresource_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalresource',
            old_name='description',
            new_name='package',
        ),
        migrations.RemoveField(
            model_name='additionalresource',
            name='name',
        ),
    ]
