# Generated by Django 5.0.2 on 2024-03-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_us', '0005_rename_description_additionalresource_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorshiptier',
            name='no_available',
            field=models.IntegerField(blank=True, help_text='Number of sponsorships available.', null=True),
        ),
    ]
