# Generated by Django 5.0.2 on 2024-03-17 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_pyconevent'),
        ('sponsor_us', '0006_alter_sponsorshiptier_no_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorshiptier',
            name='event_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsorship_tiers', to='home.eventyear'),
        ),
    ]
