# Generated by Django 5.0.2 on 2024-03-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_us', '0007_sponsorshiptier_event_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorshiptier',
            name='hex',
            field=models.CharField(default='#000', help_text='Shadow colour for tier eg, #cd7f32', max_length=25),
        ),
        migrations.AlterField(
            model_name='sponsorshiptier',
            name='colour',
            field=models.CharField(default='primary', help_text='Colour for tier eg, yellow, gray, primary etc', max_length=25),
        ),
    ]
