# Generated by Django 5.0.2 on 2024-04-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_us', '0008_sponsorshiptier_hex_alter_sponsorshiptier_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorshiptier',
            name='hex',
            field=models.CharField(default='#000', help_text='Hex colour for tier eg, #cd7f32', max_length=25),
        ),
    ]
