# Generated by Django 3.2 on 2022-11-15 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_title', models.CharField(blank=True, default='Team', help_text='Teams PyCon Africa', max_length=250)),
                ('team_image_one', models.ImageField(help_text='Upload your cover image or leave blank to use our default image', upload_to='team_page')),
                ('team_image_two', models.URLField(default='', help_text='Link to image')),
                ('section_one', markdownx.models.MarkdownxField(default='', help_text='[Supports Markdown] - PyCon Africa Team.')),
                ('session_title', models.CharField(blank=True, default='Volunteers', help_text='Session Title eg. Volunteers, Team, Mentor', max_length=250)),
                ('section_two', markdownx.models.MarkdownxField(default='', help_text='[Supports Markdown] - PyCon Africa Volunteers.')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
