# Generated by Django 5.0.2 on 2024-03-02 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_about_id_alter_team_id_alter_travel_advice_id_and_more'),
        ('home', '0008_pyconevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='event_year',
            field=models.ForeignKey(default='2024', on_delete=django.db.models.deletion.CASCADE, related_name='abouts', to='home.eventyear'),
        ),
        migrations.AddField(
            model_name='team',
            name='event_year',
            field=models.ForeignKey(default='2024', on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='home.eventyear'),
        ),
        migrations.AddField(
            model_name='travel_advice',
            name='event_year',
            field=models.ForeignKey(default='2024', on_delete=django.db.models.deletion.CASCADE, related_name='travel_advices', to='home.eventyear'),
        ),
        migrations.AddField(
            model_name='venue',
            name='event_year',
            field=models.ForeignKey(default='2024', on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='home.eventyear'),
        ),
    ]
