# Generated by Django 5.0.2 on 2024-03-02 18:18

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_about_event_year_team_event_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='about_image_two',
        ),
        migrations.AddField(
            model_name='about',
            name='about_tagline',
            field=models.CharField(blank=True, help_text='Tagline for the year', max_length=250),
        ),
        migrations.AddField(
            model_name='about',
            name='section_one_title',
            field=models.CharField(blank=True, default='WHAT IS | PYCON AFRICA?', help_text='About PyCon Africa', max_length=250),
        ),
        migrations.AddField(
            model_name='about',
            name='section_three',
            field=markdownx.models.MarkdownxField(default='', help_text='[Supports Markdown] - About PyCon Africa.'),
        ),
        migrations.AddField(
            model_name='about',
            name='section_three_title',
            field=models.CharField(blank=True, default='THE | TEAM', help_text='About PyCon Africa', max_length=250),
        ),
        migrations.AddField(
            model_name='about',
            name='section_two_title',
            field=models.CharField(blank=True, default='THE | PROGRAM', help_text='About PyCon Africa', max_length=250),
        ),
    ]
