# Generated by Django 5.0.2 on 2024-03-05 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_remove_about_about_image_two_about_about_tagline_and_more'),
        ('home', '0008_pyconevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='IOCGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event_year', models.ForeignKey(default='2024', on_delete=django.db.models.deletion.CASCADE, related_name='ioc_groups', to='home.eventyear')),
            ],
        ),
        migrations.CreateModel(
            name='IOCMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event_year', models.ForeignKey(default='2024', on_delete=django.db.models.deletion.CASCADE, related_name='ioc_members', to='home.eventyear')),
                ('groups', models.ManyToManyField(related_name='iocs', to='about.iocgroup')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event_year', models.ForeignKey(default='2024', on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_groups', to='home.eventyear')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event_year', models.ForeignKey(default='2024', on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='home.eventyear')),
                ('groups', models.ManyToManyField(related_name='volunteers', to='about.volunteergroup')),
            ],
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
