# Generated by Django 3.2 on 2022-03-30 12:45

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('privacypolicy', '0002_auto_20220330_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Privacy policies of PyCon Africa', max_length=250)),
                ('privacypolicy_policy', markdownx.models.MarkdownxField(default='', help_text='[Supports Markdown] - COC PyCon Africa.')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='privacypolicy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'privacypolicy',
                'verbose_name_plural': 'privacypolicies',
                'unique_together': {('title',)},
            },
        ),
        migrations.DeleteModel(
            name='Privacy',
        ),
    ]
