# Generated by Django 5.0.2 on 2024-02-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacypolicy', '0004_rename_privacypolicy_policy_privacypolicy_privacy_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicy',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
