# Generated by Django 3.2 on 2022-08-03 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_title', models.CharField(help_text='Ticket PyCon Africa', max_length=250)),
                ('ticket_image_one', models.ImageField(help_text='Upload your cover image or leave blank to use our default image', upload_to='ticket_page')),
                ('ticket_image_two', models.URLField(default='', help_text='Link to image')),
                ('section_one', markdownx.models.MarkdownxField(default='', help_text='[Supports Markdown] - Ticket PyCon Africa.')),
                ('section_two', markdownx.models.MarkdownxField(default='', help_text='[Supports Markdown] - Ticket PyCon Africa.')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_us', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
