# Generated by Django 5.0.2 on 2024-03-01 15:55

import django.db.models.deletion
import markdownx.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_pyconevent'),
        ('talks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='event_year',
            field=models.ForeignKey(default='', help_text='The event year this proposal is for', on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='home.eventyear'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='anything_else_you_want_to_tell_us',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Kindly add anything else you want to tell us?', null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='elevator_pitch',
            field=markdownx.models.MarkdownxField(blank=True, help_text='[Supports Markdown] - Describe your Talk to your targeted audience.', null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='link_to_preview_video_url',
            field=models.URLField(blank=True, help_text='Link to Preview video on your Youtube or Google drive'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='talk_abstract',
            field=markdownx.models.MarkdownxField(blank=True, help_text='[Supports Markdown] - Your talk_abstract.', null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='youtube_iframe_url',
            field=models.URLField(blank=True, help_text='Link to Youtube Iframe', max_length=300),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='youtube_video_url',
            field=models.URLField(blank=True, help_text='Link to Talk on youtube Video'),
        ),
        migrations.CreateModel(
            name='CFPSubmissionPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(help_text='Date and time when proposal submissions start')),
                ('end_date', models.DateTimeField(help_text='Date and time when proposal submissions end')),
                ('event_year', models.ForeignKey(default='2024', help_text='The event year this submission period is for', on_delete=django.db.models.deletion.CASCADE, related_name='submission_periods', to='home.eventyear')),
            ],
        ),
        migrations.DeleteModel(
            name='CFP',
        ),
    ]
