# Generated by Django 5.0.2 on 2024-03-02 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_pyconevent'),
        ('talks', '0002_proposal_event_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposing_talk',
            name='event_year',
            field=models.ForeignKey(default='2024', on_delete=django.db.models.deletion.CASCADE, related_name='proposing_talks', to='home.eventyear'),
        ),
        migrations.AddField(
            model_name='recording',
            name='event_year',
            field=models.ForeignKey(default='2024', on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='home.eventyear'),
        ),
        migrations.AddField(
            model_name='speak',
            name='event_year',
            field=models.ForeignKey(default='2024', on_delete=django.db.models.deletion.CASCADE, related_name='speaks', to='home.eventyear'),
        ),
    ]
