# Generated by Django 5.0.2 on 2024-04-09 21:27

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0003_proposing_talk_event_year_recording_event_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='special_requirements',
            field=markdownx.models.MarkdownxField(blank=True, help_text='If you have any special requirements such as needing travel assistance, accessibility needs, or anything else please let us know here so that we may plan accordingly. (This is not made public nor will the review committee have access to view it.)', null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='recording_release',
            field=models.BooleanField(default=True, help_text='By submitting your talk proposal, you agree to give permission to the conference organizers to record, edit, and release audio and/or video of your presentation. If you do not agree to this, please uncheck this box.'),
        ),
    ]
