# Generated by Django 5.0.2 on 2024-04-09 21:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0004_proposal_special_requirements_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='speakers',
            field=models.ManyToManyField(blank=True, related_name='speaking_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SpeakerInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('invitation_sent', models.DateTimeField(default=django.utils.timezone.now)),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talk_invitations', to=settings.AUTH_USER_MODEL)),
                ('talk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='talks.proposal')),
            ],
        ),
    ]
