# Generated by Django 5.0.2 on 2024-04-12 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0006_remove_proposal_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
