# Generated by Django 5.0.2 on 2024-04-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0008_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
